export const SIGNUP_STATUS = "SIGNUP_STATUS"
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE"
export const SIGNUP_ERROR = "SIGNUP_ERROR"


export const LOGIN_STATUS = "LOGIN_STATUS"
export const LOGIN_RESPONSE = "LOGIN_RESPONSE"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const RESET_PASSWORD_STATUS = "RESET_PASSWORD_STATUS"
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"


export const GET_USER_DETAILES = "GET_USER_DETAILES"
export const GET_USER_RESPONSE = "GET_USER_RESPONSE"
export const GET_USER_ERROR = "GET_USER_ERROR"


export const UPLOAD_IMAGE_STATUS = "UPLOAD_IMAGE_STATUS"
export const UPLOAD_IMAGE_RESPONSE = "UPLOAD_IMAGE_RESPONSE"
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR"


/**Room register action types */
export const ROOM_REGISTER_STATUS = "ROOM_REGISTER_STATUS"
export const ROOM_REGISTER_RESPONSE = "ROOM_REGISTER_RESPONSE"
export const ROOM_REGISTER_ERROR = "ROOM_REGISTER_ERROR"

export const GET_ALL_ROOM_LIST = "GET_ALL_ROOM_LIST"
export const GET_ALL_ROOM_RESPONSE = "GET_ALL_ROOM_RESPONSE"
export const GET_ALL_ROOM_ERROR = "GET_ALL_ROOM_ERROR"

/**Room place booking action */
export const BOOKING_ROOM_STATUS = "BOOKING_ROOM_STATUS"
export const BOOKING_ROOM_RESPONSE = "BOOKING_ROOM_RESPONSE"
export const BOOKING_ROOM_ERROR = "BOOKING_ROOM_ERROR"


/**Get the perticular user booked boom list */
export const GET_BOOKED_ROOM_STATUS = "GET_BOOKED_ROOM_STATUS"
export const GET_BOOKED_ROOM_RESPONSE = "GET_BOOKED_ROOM_RESPONSE"
export const GET_BOOKED_ROOM_ERROR = "GET_BOOKED_ROOM_ERROR"